version: '3.10'

services:
  db:
    container_name: larixon-postgres
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  backend:
    image: kalister/larixon_test:v.1.0
    #    build:
    #      context: ../app/
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static/
    ports:
      - '8000:8000'
    command: bash -c 'python manage.py test &&
      python manage.py makemigrations && python manage.py migrate &&
      python manage.py create_admin && python manage.py load_test_db &&
      python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - db

volumes:
  postgres_data:
  static_value:
